server:
  port: 8089
spring:
  application:
    name: hotel-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel
    username: postgres
    password: password
    flyway:
      schemas: hotel
      user: postgres
      password: password
      enabled: true
  eureka:
    client:
      healthcheck:
        enabled: true
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      hostName: ${spring.application.name}
  cloud:
    bootstrap:
      enabled: true